#!/usr/bin/env python3
"""
generate.py — Generate ligand PDB(s) from a MIF .cmap file.

Padding and origin are handled automatically by load_cmap() in data_loader.py.
The origin is always computed from the standard formula: -(size * step) / 2.

Usage:
    python generate.py \\
        --checkpoint checkpoints/best.pt \\
        --cmap /path/to/pocket.cmap \\
        --output generated.pdb \\
        --num-samples 5 \\
        --temperature 1.0 \\
        --exist-threshold 0.5
"""

import argparse
import os
from dataclasses import fields

import numpy as np
import torch

from data_loader import DataConfig, load_cmap, normalise_mif
from model import ConditionalVAE, CVaeConfig


def parse_args():
    parser = argparse.ArgumentParser(description="Generate ligand PDB from MIF grid")
    parser.add_argument("--checkpoint", required=True, help="Path to model checkpoint .pt")
    parser.add_argument("--cmap", required=True, help="Path to input .cmap file")
    parser.add_argument("--output", default="generated.pdb", help="Output PDB path")
    parser.add_argument("--num-samples", type=int, default=5, help="Number of ligands to generate")
    parser.add_argument("--temperature", type=float, default=1.0, help="Sampling temperature")
    parser.add_argument("--exist-threshold", type=float, default=0.5,
                        help="Probability threshold for keeping an atom")
    parser.add_argument("--mif-norm", default="none",
                        help="MIF normalisation strategy (must match training)")
    parser.add_argument("--coord-norm", default="centre_scale",
                        help="Coord norm strategy (must match training)")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    return parser.parse_args()


def denormalise_coords(coords_norm, cfg: DataConfig, origin: np.ndarray, step: np.ndarray,
                       grid_shape: tuple):
    """Convert model-normalised coordinates back to Ångström."""
    coords_norm = np.asarray(coords_norm, dtype=np.float64)
    origin = np.asarray(origin, dtype=np.float64)
    step = np.asarray(step, dtype=np.float64)

    if cfg.coord_norm == "centre_scale":
        physical_extent = step * (np.array(grid_shape, dtype=np.float64) - 1)
        centre = origin + physical_extent / 2.0
        half_extent = physical_extent / 2.0
        coords = coords_norm * half_extent + centre

    elif cfg.coord_norm == "voxel_index":
        coords = coords_norm * step + origin

    elif cfg.coord_norm == "none":
        coords = coords_norm

    else:
        raise ValueError(f"Unknown coord_norm: {cfg.coord_norm}")

    return coords


def sample_to_atoms(coords_norm, type_probs, exist_probs, cfg: DataConfig,
                    origin: np.ndarray, step: np.ndarray, grid_shape: tuple,
                    exist_threshold=0.5):
    """Turn one decoder output into a list of atom dicts."""
    coords_ang = denormalise_coords(coords_norm, cfg, origin, step, grid_shape)

    type_ids = np.argmax(type_probs, axis=-1)
    mask = exist_probs > exist_threshold
    indices = np.where(mask)[0]

    id_to_elem = {v: k for k, v in cfg.elem_to_id.items()}

    atoms = []
    for i in indices:
        atom_id = int(type_ids[i])
        if atom_id == cfg.pad_id:
            continue
        elem = id_to_elem.get(atom_id, "X")
        x, y, z = coords_ang[i]
        atoms.append({
            "atom_num": len(atoms) + 1,
            "name": elem,
            "res_name": "LIG",
            "chain": "A",
            "res_seq": 1,
            "x": float(x),
            "y": float(y),
            "z": float(z),
            "elem": elem,
        })
    return atoms


def write_pdb(atoms, path):
    """Write atoms to a minimal PDB file."""
    with open(path, "w") as f:
        f.write("REMARK   1 GENERATED BY CONDITIONAL VAE\n")
        for a in atoms:
            # PDB ATOM format (columns are roughly fixed-width)
            f.write(
                f"ATOM  {a['atom_num']:5d} {a['name']:4s} {a['res_name']:3s} "
                f"{a['chain']:1s}{a['res_seq']:4d}    "
                f"{a['x']:8.3f}{a['y']:8.3f}{a['z']:8.3f}"
                f"  1.00  0.00          {a['elem']:>2s}  \n"
            )
        f.write("END\n")
    print(f"Wrote {len(atoms)} atoms to {path}")


def _load_data_config(checkpoint: dict, args) -> DataConfig:
    """Rebuild DataConfig from checkpoint or fall back to args."""
    if "data_config_dict" in checkpoint:
        # Filter to fields that exist in the current DataConfig dataclass
        # so adding new fields later doesn't break old checkpoints.
        valid_keys = {f.name for f in fields(DataConfig) if f.init}
        filtered = {k: v for k, v in checkpoint["data_config_dict"].items()
                    if k in valid_keys}
        data_cfg = DataConfig(**filtered)
        print("  Loaded DataConfig from checkpoint.")
        return data_cfg

    print("  WARNING: DataConfig not found in checkpoint — reconstructing from args.")
    print("  For exact reproduction, save data_cfg.__dict__ during training.")

    # Fallback: infer what we can from the model config, fill the rest from CLI.
    # This assumes training used the default atom_types list.
    return DataConfig(
        expected_grid_shape=checkpoint.get("config_dict", {}).get("input_shape", (128, 128, 128)),
        num_channels=checkpoint.get("config_dict", {}).get("in_channels", 5),
        max_atoms=checkpoint.get("config_dict", {}).get("max_atoms", 96),
        mif_norm=args.mif_norm,
        coord_norm=args.coord_norm,
        voxel_spacing=0.25,          # fallback; only used if step is missing from file
        batch_size=1,
        num_workers=0,
        val_fraction=0.0,
    )


def main():
    args = parse_args()
    device = torch.device(args.device)

    # ── Load checkpoint ──
    print(f"Loading checkpoint from {args.checkpoint} ...")
    checkpoint = torch.load(args.checkpoint, map_location=device)

    if not isinstance(checkpoint, dict):
        raise ValueError("Checkpoint is not a dict. Expected training checkpoint format.")

    # Extract model weights (unwrap from training wrapper)
    if "model_state_dict" in checkpoint:
        state_dict = checkpoint["model_state_dict"]
    elif "state_dict" in checkpoint:
        state_dict = checkpoint["state_dict"]
    else:
        raise KeyError("Checkpoint missing 'model_state_dict' or 'state_dict'.")

    # Extract/reconstruct model config
    if "config_dict" in checkpoint:
        model_cfg = CVaeConfig(**checkpoint["config_dict"])
        print("  Reconstructed model config from checkpoint.")
    elif "model_cfg" in checkpoint:
        model_cfg = checkpoint["model_cfg"]
    else:
        raise KeyError(
            "Checkpoint missing 'config_dict'. Cannot reconstruct model architecture.\n"
            "Ensure your training script saves the model config."
        )

    print(f"  Model config: {model_cfg}")

    # Build model and load weights
    model = ConditionalVAE(model_cfg).to(device)
    model.load_state_dict(state_dict, strict=True)
    model.eval()

    # ── Build DataConfig (must match training normalisation) ──
    data_cfg = _load_data_config(checkpoint, args)
    print(f"  DataConfig: mif_norm={data_cfg.mif_norm}, coord_norm={data_cfg.coord_norm}, "
          f"voxel_spacing={data_cfg.voxel_spacing}")

    # ── Load MIF grid ──
    # load_cmap automatically centre-pads or crops to expected_shape.
    # The origin is computed from the standard formula: -(size * step) / 2
    print(f"Loading MIF grid from {args.cmap} ...")
    grid, origin, step = load_cmap(
        args.cmap,
        dataset_path=data_cfg.dataset_path,   # None → auto-detect channels
        expected_shape=data_cfg.expected_grid_shape,
        num_channels=data_cfg.num_channels,
        fallback_step=data_cfg.voxel_spacing,
    )

    grid = normalise_mif(grid, data_cfg)
    grid = torch.from_numpy(grid).unsqueeze(0).float().to(device)

    print(f"  Grid shape: {tuple(grid.shape)}")
    print(f"  Origin:     {origin}")
    print(f"  Step:       {step}")

    # ── Generate ──
    print(f"Generating {args.num_samples} sample(s) at temperature={args.temperature} ...")
    with torch.no_grad():
        # NOTE: if your model.generate() returns raw logits, apply
        # torch.sigmoid(exist_logits) and torch.softmax(type_logits, dim=-1)
        # before passing to sample_to_atoms().
        coords, type_probs, exist_probs = model.generate(
            grid,
            num_samples=args.num_samples,
            temperature=args.temperature,
        )

    # ── Write PDBs ──
    grid_shape = data_cfg.expected_grid_shape
    base, ext = os.path.splitext(args.output)
    for s in range(args.num_samples):
        atoms = sample_to_atoms(
            coords[s].cpu().numpy(),
            type_probs[s].cpu().numpy(),
            exist_probs[s].cpu().numpy(),
            data_cfg,
            origin=origin,
            step=step,
            grid_shape=grid_shape,
            exist_threshold=args.exist_threshold,
        )

        out_path = f"{base}_{s}{ext}" if args.num_samples > 1 else args.output
        if len(atoms) == 0:
            print(f"Sample {s}: no atoms passed existence threshold — skipping.")
            continue

        write_pdb(atoms, out_path)
        print(f"Sample {s}: {len(atoms)} atoms")

    print("Done.")


if __name__ == "__main__":
    main()
